
###  CONFIG

$ yum list installed ansible

$ yum install ansible

$ ansible --version

$ vim ansible.cfg
    [defaults]
    remote_user = labo
    inventory = inventory

    [privilege_escalation]
    become = False
    become_method = sudo
    become_user = root
    become_ask_pass = False


### INVENTAIRE 

$ ansible-inventory --list

$ ansible-inventory  --host labo-win-1.pldomain


### Ad-HOC COMMANDS

$ ansible all -m command -a 'id'

$ ansible all -b -m command -a 'id'

$ ansible CentOS -b -m copy -a 'content="This server is managed by Ansible with user {{ ansible_user }}.\n" dest=/etc/motd'

$ ansible CentOS -a 'cat /etc/motd'

$ ansible Windows -m win_whoami

$ ansible Windows -m win_shell -a "ls C:/users"

$ ansible labo-win-1.pldomain -m ansible.windows.win_copy -a 'content="This server is managed by Ansible and i am {{ ansible_user }}\n" dest="C:\users\labo\Desktop\{{ moi }}.txt"'

$ ansible labo-win-1.pldomain -m ansible.windows.win_file -a 'dest=C:\users\labo\Desktop\{{ moi }}.txt state=absent'

