---
## $ansible-playbook --syntax-check playbok.yml

- name: Enable internet services
  hosts: host.pldomain
  become: yes

  tasks:
    - name: latest version of all required packages installed
      yum:
        name:
          - firewalld
          - httpd
        state: latest

    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: test php page is installed
      get_url:
        url: "http://materials.example.com/grading/var/www/html/index.php"
        dest: /var/www/html/index.php
        mode: 0644

- name: Test internet web server
  hosts: localhost
  become: no

  tasks:
    - name: connect to internet web server
      uri:
        url: "http://{{ inventory_hostname }}"
        status_code: 200

