---
# Playbook to address dns local issue with corporate laptops

- hosts: localhost
  connection: local
  become: true
  vars:
    etat: present
  tasks:

  - name: add lines in /etc/hosts to reach vm's
    lineinfile:
      path: /etc/hosts
      line: "{{ item.ip }}       {{ item.dns }}"
      state: "{{ etat }}"
    loop:
      - { ip: "172.16.16.100", dns: "labo-lin-test.pldomain" }
      - { ip: "172.16.16.101", dns: "labo-win-test.pldomain" }
      
