---
# Playbook to address dns local issue with corporate laptops

- hosts: all
  serial: 1
  gather_facts: false
  tasks:

  - name: add lines in /etc/hosts to reach vm's
    lineinfile:
      path: /etc/hosts
      line: "{{ hostvars[inventory_hostname].ansible_host }}       {{ inventory_hostname }}"
      state: "{{ state | d('present') }}"
    delegate_to: localhost
    connection: local
    become: true
    
