---
## $ansible-playbook --syntax-check playbok.yml

- name: Enable internet services
  hosts: CentOS
  become: yes

  tasks:
    - name: ensure latest version of all required packages installed
      yum:
        name:
          - firewalld
          - httpd
        state: latest

    - name: firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: test index page is installed
      copy:
        dest: /var/www/html/index.html
        mode: 0644
        content: |
          IO

    - name: connect to test internet web server
      uri:
        url: "http://{{ inventory_hostname }}"
        status_code: 200
      delegate_to: localhost

