---
- hosts: localhost
  connection: local
  become: true
  tasks:
  
  
  - name: install python3
    package:
      name: python3-pip,sshpass
      state: present

  - name: install pip dependencies
    pip:
      name:
        - pywinrm
      state: present

  - name: install galaxy collections
    command:
      ansible-galaxy collection install community.windows  --ignore-certs
      
